# Generated by Django 2.1.2 on 2018-10-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
