# Generated by Django 2.1.2 on 2018-10-29 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='std_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
